### ISSUE TITLE
Petition to not Brute Force Switch statements

### ISSUE THREAD

**Issue by filipeqm94** [v-wang/farkle#1]
https://github.com/v-wang/farkle/blob/341a826350931039defb7b32814bc083eefaef36/farkle.js#L70

If you're running this switch statement regardless of what is being passed to it, it would be best practice to use `if` statements.

**Comment by v-wang** [comment]
Should have just done this instead, oh well: 

const scoreGuide = {
  1: { 1: 100, 2: 200, 3: 1000, 4: 1100, 5: 1200, 6: 2000 },
  2: { 3: 200 },
  3: { 3: 300 },
  4: { 3: 400 },
  5: { 1: 50, 2: 100, 3: 500, 4: 550, 5: 600, 6: 1000 },
  6: { 3: 600 },
};
