### ISSUE TITLE
`var` Keyword assigns variables to the Global Scope !! CAREFUL !!

### ISSUE THREAD

**Issue by filipeqm94** [v-wang/farkle#2]
https://github.com/v-wang/farkle/blob/341a826350931039defb7b32814bc083eefaef36/farkle.js#L8

When you use `var` to assign `i` inside of `for` loops you still assign the variable to the global scope. Use with caution, since it can be cause unwanted behavior.

```js
for (var i = 0; i < 5; i++) {
    // do something
}

console.log(i) // output: 5
```

Would recommend the usage of the `let` keyword to avoid possible unwanted behavior.

**Comment by filipeqm94** [comment]
https://github.com/v-wang/farkle/blob/341a826350931039defb7b32814bc083eefaef36/farkle.js#L49

This can be very dangerous on large scale application. The variable has the same name as the iteration variable.

**Comment by v-wang** [comment]
Yeah, that's just how it was given to me - had to choose what I can work on given the time
